version: "3.9"
services:
  devsu-db:
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: basedatos
    volumes:
      - ./path/to/sql/script:/docker-entrypoint-initdb.d

  personas:
    build: ./personas
    ports:
      - "8082:8082"
    depends_on:
      - devsu-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://devsu-db:3306/basedatos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

  cuentas:
    build: ./cuentas
    ports:
      - "8083:8083"
    depends_on:
      - devsu-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://devsu-db:3306/basedatos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin      

